"""Merge DAIGT V2 and LLM-Detect into one corpus with trustworthy topic labels.

Why a merge rather than a concatenation. Roughly two thirds of LLM-Detect is
already present in DAIGT V2, so stacking the two files would place the same
essay in the corpus twice, and a later split could then put one copy in
training and the other in test. That is the leak this study exists to
criticise, so essays are deduplicated on normalised text.

Why DAIGT supplies the topic labels. LLM-Detect ships no topic column. The
labels previously recovered for it assumed the corpus held two topics, which
is true of the official competition file but not of the community-assembled
file used here: checked against DAIGT, only 24% of the essays labelled
"car essay" are about car-free cities. Those recovered labels are therefore
discarded and DAIGT's own prompt_name is used instead.

What LLM-Detect still contributes. Around 9,500 essays absent from DAIGT,
most of them generated by PaLM 2, Gemini and GPT-4, which DAIGT does not
cover. Their topic is taken from DAIGT where the essay is shared, and is
otherwise left unknown rather than guessed.

Output: datasets/merged/essays_merged.csv
"""

import hashlib
import os
import re

import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DAIGT = os.path.join(REPO, 'datasets', 'DAIGT V2', 'train_v2_drcat_02.csv')
LLMD = os.path.join(REPO, 'datasets', 'llm_detect', 'Training_Essay_Data.csv')
OUTDIR = os.path.join(REPO, 'datasets', 'merged')
OUT = os.path.join(OUTDIR, 'essays_merged.csv')

MIN_CHARS = 100


def norm(s):
    return hashlib.md5(str(s).strip().lower().encode('utf8', 'ignore')).hexdigest()


def slug(name):
    s = re.sub(r'[^a-z0-9]+', '_', str(name).lower()).strip('_')
    return s[:40]


def main():
    os.makedirs(OUTDIR, exist_ok=True)

    # ---------------------------------------------------------------- DAIGT
    dg = pd.read_csv(DAIGT)
    dg = dg.rename(columns={'prompt_name': 'topic', 'source': 'generator'})
    dg['origin'] = 'daigt'
    dg = dg[['text', 'label', 'topic', 'generator', 'origin']]
    print('DAIGT V2      : %6d rows' % len(dg))

    # ---------------------------------------------------------------- LLM-Detect
    ld = pd.read_csv(LLMD)
    tcol = 'text' if 'text' in ld.columns else ld.columns[0]
    lcol = ('generated' if 'generated' in ld.columns
            else 'label' if 'label' in ld.columns else ld.columns[1])
    ld = ld.rename(columns={tcol: 'text', lcol: 'label'})
    ld['topic'] = pd.NA          # no trustworthy topic in this file
    ld['generator'] = pd.NA
    ld['origin'] = 'llm_detect'
    ld = ld[['text', 'label', 'topic', 'generator', 'origin']]
    print('LLM-Detect    : %6d rows' % len(ld))

    # ---------------------------------------------------------------- merge
    both = pd.concat([dg, ld], ignore_index=True)
    both['text'] = both['text'].astype(str)
    both = both[both['text'].str.len() >= MIN_CHARS]
    both['H'] = both['text'].map(norm)
    both['label'] = pd.to_numeric(both['label'], errors='coerce').astype('Int64')
    both = both.dropna(subset=['label'])

    # a label conflict means the same text is marked both ways: drop it
    conflict = both.groupby('H')['label'].nunique()
    bad = set(conflict[conflict > 1].index)
    if bad:
        print('dropped %d texts with conflicting labels' % len(bad))
        both = both[~both['H'].isin(bad)]

    # DAIGT rows sort first, so the surviving copy keeps DAIGT's topic
    both['pref'] = (both['origin'] != 'daigt').astype(int)
    both = both.sort_values(['H', 'pref'])

    shared = both.groupby('H')['origin'].nunique()
    in_both = set(shared[shared > 1].index)

    merged = both.drop_duplicates('H', keep='first').copy()
    merged['origin'] = merged['H'].map(
        lambda k: 'both' if k in in_both else None).fillna(merged['origin'])

    merged['generator'] = merged['generator'].fillna('unknown')
    merged.loc[merged['label'] == 0, 'generator'] = 'student'

    # topic ids, ordered by volume so 00 is the largest topic
    counts = merged['topic'].value_counts()
    ids = {t: i for i, t in enumerate(counts.index)}
    merged['topic_id'] = merged['topic'].map(ids).astype('Int64')
    merged['topic_slug'] = merged['topic'].map(
        lambda t: slug(t) if pd.notna(t) else pd.NA)

    merged['uid'] = merged['H']
    merged = merged[['uid', 'text', 'label', 'topic', 'topic_id',
                     'topic_slug', 'generator', 'origin']]
    merged = merged.sample(frac=1, random_state=42).reset_index(drop=True)
    merged.to_csv(OUT, index=False)

    # ---------------------------------------------------------------- report
    print()
    print('MERGED        : %6d unique essays  ->  %s' % (len(merged), OUT))
    print()
    print('by origin:')
    print(merged['origin'].value_counts().to_string())
    print()
    print('by label:')
    print(merged['label'].value_counts().rename({0: 'student', 1: 'AI'}).to_string())
    print()
    ct = pd.crosstab(merged['topic'].fillna('(unknown)'), merged['label'])
    ct.columns = ['student', 'AI']
    ct['total'] = ct.sum(1)
    ct['smaller_class'] = ct[['student', 'AI']].min(1)
    ct.insert(0, 'id', [ids.get(t, -1) for t in ct.index])
    print('by topic:')
    print(ct.sort_values('total', ascending=False).to_string())
    print()
    usable = ct[(ct.index != '(unknown)') & (ct['smaller_class'] >= 300)]
    print('topics usable for a leave-one-topic-out design (>=300 both classes): %d'
          % len(usable))

    ct.to_csv(os.path.join(OUTDIR, 'topic_summary.csv'))


if __name__ == '__main__':
    main()
